// In reference to https://susrrpo.docs.apiary.io/#/data-structures/0/timed-value-entry
export interface TimedValuedEntry {
  validFrom: string,
  validTo?: string
}
/* Generated by https://transform.tools/json-to-typescript from tipical response from RPO API
 * Some fields extend TimedValuedEntry for generic function needs
*/

export interface RpoRawData {
  results: Result[]
  license: string
}

export interface Result {
  id: number
  dbModificationDate: string
  identifiers: Identifier[]
  fullNames: FullName[]
  addresses: Address[]
  establishment: string
  termination?: string
  sourceRegister: SourceRegister
}

export interface Identifier extends TimedValuedEntry {
  value: string
}

export interface FullName extends TimedValuedEntry {
  value: string
}

export interface Address extends TimedValuedEntry {
  street?: string
  regNumber: number
  buildingNumber?: string
  postalCodes?: string[]
  municipality: Municipality
  country: Country
  district?: District
  buildingIndex?: string
  formatedAddress?: string
}

export interface Municipality {
  value: string
  code?: string
  codelistCode?: string
}

export interface Country {
  value: string
  code: string
  codelistCode: string
}

export interface District {
  value: string
  code?: string
  codelistCode?: string
}

export interface SourceRegister {
  value: Value
  registrationOffices: RegistrationOffice[]
  registrationNumbers: RegistrationNumber[]
}

export interface Value {
  value: string
  code: string
  codelistCode: string
}

export interface RegistrationOffice extends TimedValuedEntry {
  value: string
}

export interface RegistrationNumber {
  value: string
}

